#!/usr/bin/env zsh

emulate -L zsh -o err_return

local script
script=$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)
zsh -c "$script" "" --unattended --skip-chsh &>/dev/null </dev/null
