#!/bin/zsh
export BROWSER=links
if [ -x /usr/bin/lesspipe.sh ] && [ -x /usr/bin/source-highlight ];then
	export LESSOPEN='|file=%s; /usr/bin/source-highlight -q --infer-lang -f esc --style-file=esc.style -i "$file" 2>/dev/null | /usr/bin/ifne -n /usr/bin/lesspipe.sh "$file" '
fi
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
if [ "$ZSH_ARGZERO" = "zsh" ];then
	export LS_COLORS=${(@f)$(dircolors -c ~/.shell/dircolors 2>/dev/null || dircolors -c 2>/dev/null)[3]//\'/}
fi

