#!/bin/zsh
export BROWSER=firefox
export TERMINAL="xfce4-terminal"
if [ "${DESKTOP_SESSION:-${XDG_SESSION_DESKTOP}}" != "plasma" ];then
	export QT_QPA_PLATFORMTHEME=qt5ct
	export QT_SCALE_FACTOR=1
fi

#export ENABLE_VKBASALT=1
export MANGOHUD=1
#export mesa_glthread=true
#export MESA_LOADER_DRIVER_OVERRIDE=zink

#export DXVK_LOG_LEVEL=error
export WINEDEBUG=-all
export WINEESYNC=1
export WINEFSYNC=1
export EOS_YAD_TERMINAL=kitty
if [ -z "$WINEARCH" ]; then
	export WINEARCH=win64
fi
if [ -d /mnt/Games/wine ]; then
	export WINEPREFIX=/mnt/Games/wine
fi
