#!/bin/zsh
function zplug:post:zinsults {
	zinsults_load=('default' 'shakespeare')
}

function zplug:post:autoswitch_virtualenv {
	VIRTUAL_ENV_DISABLE_PROMPT=1
}

function zplug:post:fast-syntax-highlighting {
	((${+aliases[fsh-alias]})) && \
	unalias fsh-alias
}

function zplug:pre:hacker-quotes {
	ZSH_HACKER_QUOTES_ENABLE_WHEN_INTERACTIVE=1
}

function zplug:post:hacker-quotes {
	unset ZSH_HACKER_QUOTES_ENABLE_WHEN_INTERACTIVE
}

function zplug:post:bd {
	unalias .. ... ....
}

function zplug:post:auto-notify {
	AUTO_NOTIFY_THRESHOLD=20
	AUTO_NOTIFY_EXPIRE_TIME=5000
	AUTO_NOTIFY_WHITELIST=()
	AUTO_NOTIFY_IGNORE+=(
		man info
		gcc g++ pbi wormhole
		shit danime git
		nano xed gedit vi vim
		vlc mpv celluloid
		yay pacman bc
	)
}

function zplug:post:autosuggestions {
	ZSH_AUTOSUGGEST_STRATEGY=(history completion)
	ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
}

function zplug:post:you-should-use {
	YSU_MESSAGE_POSITION=after
#	YSU_HARDCORE=1
	YSU_MESSAGE_FORMAT="$(print -P %B%F{cyan})Use \"$(print -P %F{blue})%alias$(print -P %F{cyan})\", $(print -P %F{red})you little shit!$(print -P %b%f)"
	function ysu:start { enable_you_should_use; }
	function ysu:stop { disable_you_should_use; }
	function ysu:stat {
		echo YSU Stats
		check_alias_usage 2>&1|grep -v 'entry='
	}
}

function zplug:post:zshmarks {
	alias jmp=jump
	alias mark=bookmark
	alias unmark=deletemark
	alias lsmark=showmarks
}

function zplug:post:history-substring-search {
	bindkey "$terminfo[kcuu1]" history-substring-search-up
	bindkey "$terminfo[kcud1]" history-substring-search-down
}

function zplug:post:command-time {
	ZSH_COMMAND_TIME_MSG="Execution time: %s"
	ZSH_COMMAND_TIME_COLOR=cyan
}

function zplug:post:gitstatus-async {
	GITSTATUS[seperator]="${ENV[prompt_seperator]}"
	GITSTATUS[prefix]="${ENV[prompt_prefix]}"
	GITSTATUS[suffix]="${ENV[prompt_suffix]}"
}

function zplug:post:devprompt {
	DEVPROMPT[seperator]="${ENV[prompt_seperator]}"
	DEVPROMPT[prefix]="${ENV[prompt_prefix]}"
	DEVPROMPT[suffix]="${ENV[prompt_suffix]}"
}

function zplug:pre:git {
	source $ZDOTDIR/omz/lib/git.zsh
}

function zplug:post:dotenv {
	alias dotenv=source_env
}
