#!/bin/sh

set -ue

printf '==> setting up a container ...\n'

aptget() {
  DEBIAN_FRONTEND=noninteractive DEBCONF_NOWARNINGS=yes \
    command apt-get                                     \
    -o DPkg::options::="--force-confdef"                \
    -o DPkg::options::="--force-confold"                \
    -qq "$@" >/dev/null
}

aptget update
aptget upgrade -y
aptget install -y -- bsdutils curl git make ncurses-bin perl sudo util-linux zsh direnv tzdata "$@"
[ $# -eq 0 ] || aptget update

starship="$(curl -fsSL https://starship.rs/install.sh)"
sh -c "$starship" sh -y >/dev/null

dir="$(dirname -- "$0")"
"$dir"/install-tmux

git config --system core.untrackedCache true
